import { 
  University, Faculty, Department, Role, Permission,
  Location, Asset, RequestItem, TransferItem
} from '../types';

export const universitiesSeed: University[] = [
  { id: 'univ-1', name: 'Central State University', code: 'CSU' },
  { id: 'univ-ext', name: 'External Partner University', code: 'EPU' },
];

export const facultiesSeed: Faculty[] = [
  { id: 'fac-fet', university_id: 'univ-1', name: 'Faculty of Engineering & Technology', code: 'FET' },
  { id: 'fac-fos', university_id: 'univ-1', name: 'Faculty of Science', code: 'FOS' },
  { id: 'fac-ext', university_id: 'univ-ext', name: 'External Faculty of Medicine', code: 'EFM' },
];

export const departmentsSeed: Department[] = [
  { id: 'dept-cse', faculty_id: 'fac-fet', name: 'Computer Science & Engineering', code: 'CSE' },
  { id: 'dept-ee', faculty_id: 'fac-fet', name: 'Electrical & Electronic Engineering', code: 'EE' },
  { id: 'dept-phys', faculty_id: 'fac-fos', name: 'Department of Physics', code: 'PHYS' },
  { id: 'dept-chem', faculty_id: 'fac-fos', name: 'Department of Chemistry', code: 'CHEM' },
  { id: 'dept-ext', faculty_id: 'fac-ext', name: 'External Medical Research', code: 'EXT' },
];

export const rolesSeed: Role[] = [
  { id: 'IT_GROUP_MEMBER', name: 'IT Group Member', description: 'Technical specialist for infrastructure and authorized location creation.', default_level: 2 },
  { id: 'DEPARTMENT_ADMIN', name: 'Department Administrator (DA)', description: 'Department-level asset manager and first-tier transfer approver.', default_level: 1 },
  { id: 'FACULTY_ADMIN', name: 'Faculty Administrator / Dean', description: 'Faculty-level manager and cross-department transfer approver.', default_level: 2 },
  { id: 'UNIVERSITY_ADMIN', name: 'University Administrator', description: 'Central campus governance, policy, and cross-faculty approver.', default_level: 3 },
  { id: 'STANDARD_USER', name: 'Standard User (Level 0)', description: 'Student or basic staff member, restricted to Basic request forms.', default_level: 0 },
  { id: 'RESEARCH_STAFF', name: 'Senior Researcher (Level 1)', description: 'Academic and research personnel eligible for Advanced forms.', default_level: 1 },
];

export const permissionsSeed: Permission[] = [
  { id: 'view_inventory', name: 'View Inventory', category: 'Inventory', description: 'View organization assets and details.' },
  { id: 'manage_assets', name: 'Manage Assets', category: 'Inventory', description: 'Create and edit assets within authorized scope.' },
  { id: 'create_locations', name: 'Create Locations', category: 'Locations', description: 'Create new rooms/locations (requires approved exception).' },
  { id: 'create_advanced_requests', name: 'Advanced Request Form', category: 'Requests', description: 'Access advanced request forms for specialized assets.' },
  { id: 'create_exception_requests', name: 'Exception Request Form', category: 'Requests', description: 'Access exception request forms for special allocations.' },
  { id: 'approve_department_transfers', name: 'Approve Department Transfers', category: 'Transfers', description: 'Approve transfers within the same faculty.' },
  { id: 'approve_faculty_transfers', name: 'Approve Faculty Transfers', category: 'Transfers', description: 'Approve transfers across faculties.' },
  { id: 'approve_university_transfers', name: 'Approve University Transfers', category: 'Transfers', description: 'Approve transfers outside the university.' },
  { id: 'approve_requests', name: 'Approve Borrow/Reservation Requests', category: 'Requests', description: 'Approve or reject borrow and reservation requests.' },
  { id: 'delegate_permissions', name: 'Delegate Permissions', category: 'Administration', description: 'Delegate own permissions to other users without escalation.' },
];

export const initialLocations: Location[] = [
  {
    id: 'loc-lab101',
    name: 'Computer Systems Lab',
    building: 'Turing Hall',
    room: 'Room 101',
    department_id: 'dept-cse',
    is_active: true,
  },
  {
    id: 'loc-server1',
    name: 'Central Server Room',
    building: 'Ada Lovelace Complex',
    room: 'Room S-01',
    department_id: 'dept-cse',
    is_active: true,
  },
  {
    id: 'loc-ee201',
    name: 'Circuits & Power Lab',
    building: 'Faraday Hall',
    room: 'Room 201',
    department_id: 'dept-ee',
    is_active: true,
  },
  {
    id: 'loc-phys301',
    name: 'Optics & Laser Lab',
    building: 'Newton Hall',
    room: 'Room 301',
    department_id: 'dept-phys',
    is_active: true,
  },
  {
    id: 'loc-chem105',
    name: 'Analytical Chemistry Lab',
    building: 'Curie Hall',
    room: 'Room 105',
    department_id: 'dept-chem',
    is_active: true,
  },
];

export const initialAssets: Asset[] = [
  {
    id: 'AST-CSE-001',
    name: 'High-Performance AI Compute Server',
    description: '4x RTX 6000 Ada GPU Server for Deep Learning research',
    category: 'IT Equipment',
    department_id: 'dept-cse',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    location_id: 'loc-server1',
    condition: 'NEW',
    status: 'AVAILABLE',
    created_at: '2025-01-10T09:00:00Z',
    updated_at: '2025-01-10T09:00:00Z',
  },
  {
    id: 'AST-CSE-002',
    name: 'VR Simulation Headset Kit',
    description: 'Enterprise VR development headset with 6-DOF tracking',
    category: 'Lab Equipment',
    department_id: 'dept-cse',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    location_id: 'loc-lab101',
    condition: 'GOOD',
    status: 'AVAILABLE',
    created_at: '2025-01-15T10:30:00Z',
    updated_at: '2025-01-15T10:30:00Z',
  },
  {
    id: 'AST-CSE-003',
    name: 'Enterprise 48-Port Managed Switch',
    description: 'Cisco Catalyst 10GbE Switch for Lab Infrastructure',
    category: 'IT Equipment',
    department_id: 'dept-cse',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    location_id: 'loc-server1',
    condition: 'GOOD',
    status: 'IN_USE',
    created_at: '2025-01-20T14:00:00Z',
    updated_at: '2025-01-20T14:00:00Z',
  },
  {
    id: 'AST-EE-001',
    name: 'Digital Storage Oscilloscope 500MHz',
    description: '4-Channel Mixed Signal Oscilloscope with logic probes',
    category: 'Lab Equipment',
    department_id: 'dept-ee',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    location_id: 'loc-ee201',
    condition: 'GOOD',
    status: 'AVAILABLE',
    created_at: '2025-02-01T11:00:00Z',
    updated_at: '2025-02-01T11:00:00Z',
  },
  {
    id: 'AST-PHYS-001',
    name: 'High-Vacuum Spectrometer',
    description: 'Ultraviolet and visible light vacuum spectrometer',
    category: 'Lab Equipment',
    department_id: 'dept-phys',
    faculty_id: 'fac-fos',
    university_id: 'univ-1',
    location_id: 'loc-phys301',
    condition: 'FAIR',
    status: 'AVAILABLE',
    created_at: '2025-02-05T08:45:00Z',
    updated_at: '2025-02-05T08:45:00Z',
  },
  {
    id: 'AST-CHEM-001',
    name: 'Gas Chromatography-Mass Spectrometer',
    description: 'Benchtop GC-MS instrument for organic chemical analysis',
    category: 'Lab Equipment',
    department_id: 'dept-chem',
    faculty_id: 'fac-fos',
    university_id: 'univ-1',
    location_id: 'loc-chem105',
    condition: 'UNDER_MAINTENANCE',
    status: 'UNDER_MAINTENANCE',
    created_at: '2025-02-12T13:15:00Z',
    updated_at: '2025-02-12T13:15:00Z',
  },
];

export const initialRequests: RequestItem[] = [
  {
    id: 'req-exc-001',
    request_number: 'REQ-EXC-2025-001',
    request_type: 'CREATE_LOCATION_EXCEPTION',
    form_type: 'EXCEPTION',
    user_id: 'user-res-01',
    start_date: '2025-03-01T00:00:00Z',
    end_date: '2026-03-01T00:00:00Z',
    purpose: 'Authorization for New Robotics & Autonomous Systems Testing Bay',
    special_justification: 'Approved by Dean for multi-disciplinary autonomous drone and robotics testing under Grant #ROB-2025.',
    status: 'APPROVED', // Ready for IT group member to build location!
    department_id: 'dept-cse',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    created_at: '2025-02-20T10:00:00Z',
    updated_at: '2025-02-21T14:30:00Z',
  },
  {
    id: 'req-exc-002',
    request_number: 'REQ-EXC-2025-002',
    request_type: 'CREATE_LOCATION_EXCEPTION',
    form_type: 'EXCEPTION',
    user_id: 'user-res-01',
    start_date: '2025-04-01T00:00:00Z',
    end_date: '2026-04-01T00:00:00Z',
    purpose: 'Expansion of Server Annex Storage Area',
    special_justification: 'Pending department committee review.',
    status: 'PENDING', // Unapproved exception request - test that IT cannot use this until approved!
    department_id: 'dept-cse',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    created_at: '2025-02-25T09:15:00Z',
    updated_at: '2025-02-25T09:15:00Z',
  },
  {
    id: 'req-bor-001',
    request_number: 'REQ-BOR-2025-001',
    request_type: 'BORROW_ASSET',
    form_type: 'BASIC',
    user_id: 'user-std-01',
    asset_id: 'AST-CSE-002',
    start_date: '2025-03-10T10:00:00Z',
    end_date: '2025-03-15T18:00:00Z',
    purpose: 'Senior Capstone Project VR testing session',
    status: 'PENDING',
    department_id: 'dept-cse',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    created_at: '2025-02-26T16:00:00Z',
    updated_at: '2025-02-26T16:00:00Z',
  },
  {
    id: 'req-res-001',
    request_number: 'REQ-RES-2025-001',
    request_type: 'RESERVE_LOCATION',
    form_type: 'ADVANCED',
    user_id: 'user-res-01',
    location_id: 'loc-lab101',
    start_date: '2025-03-20T08:00:00Z',
    end_date: '2025-03-22T20:00:00Z',
    purpose: 'High-throughput parallel algorithm workshop and lab reservation',
    special_justification: 'Requires exclusive lab access during multi-core benchmarking run.',
    status: 'PENDING',
    department_id: 'dept-cse',
    faculty_id: 'fac-fet',
    university_id: 'univ-1',
    created_at: '2025-02-27T11:20:00Z',
    updated_at: '2025-02-27T11:20:00Z',
  },
];

export const initialTransfers: TransferItem[] = [
  {
    id: 'trf-001',
    transfer_number: 'TRF-2025-001',
    asset_id: 'AST-CSE-003',
    source_department_id: 'dept-cse',
    destination_department_id: 'dept-cse',
    destination_faculty_id: 'fac-fet',
    destination_university_id: 'univ-1',
    destination_location_id: 'loc-lab101',
    transfer_type: 'SAME_DEPARTMENT',
    status: 'COMPLETED',
    requested_by: 'user-da-cse',
    notes: 'Relocated switch from server room to Lab 101 rack for high-speed connectivity.',
    created_at: '2025-02-15T10:00:00Z',
    updated_at: '2025-02-15T10:00:00Z',
  },
  {
    id: 'trf-002',
    transfer_number: 'TRF-2025-002',
    asset_id: 'AST-EE-001',
    source_department_id: 'dept-ee',
    destination_department_id: 'dept-cse',
    destination_faculty_id: 'fac-fet',
    destination_university_id: 'univ-1',
    destination_location_id: 'loc-lab101',
    transfer_type: 'DIFF_DEPT_SAME_FACULTY',
    status: 'PENDING_DA_APPROVAL',
    requested_by: 'user-res-01',
    notes: 'Temporary transfer for embedded systems sensor debugging in CSE lab.',
    created_at: '2025-02-26T14:30:00Z',
    updated_at: '2025-02-26T14:30:00Z',
  },
  {
    id: 'trf-003',
    transfer_number: 'TRF-2025-003',
    asset_id: 'AST-PHYS-001',
    source_department_id: 'dept-phys',
    destination_department_id: 'dept-ee',
    destination_faculty_id: 'fac-fet',
    destination_university_id: 'univ-1',
    destination_location_id: 'loc-ee201',
    transfer_type: 'DIFF_FACULTY',
    status: 'PENDING_FACULTY_APPROVAL',
    requested_by: 'user-dean-fet',
    notes: 'Inter-faculty equipment loan for optoelectronics research collaboration.',
    created_at: '2025-02-27T09:00:00Z',
    updated_at: '2025-02-27T09:00:00Z',
  },
];
